import json, sys
src, out = sys.argv[1], sys.argv[2]
ru = sys.argv[3] == 'ru'
d = json.load(open(src, encoding='utf-8'))
R = {
 "role.vaz2109.mechanic.p1": ("Всегда «Спешка I»: копает и работает быстрее", "Always Haste I: digs and works faster"),
 "role.vaz2109.mechanic.p2": ("На верстаке механика в 25% случаев выходит вторая штука (кроме ВАЗа и огнестрела)", "25% chance of a second item at the mechanic's bench (not cars or firearms)"),
 "role.vaz2109.frog.p1": ("Всегда «Прыгучесть II»; в воде «Грация дельфина», а мокрым бегает и плавает на 15% быстрее", "Always Jump Boost II; Dolphin's Grace in water and 15% faster while wet"),
 "role.vaz2109.vessel.p1": ("Пальцы Сукуны дают здоровье и урон (+0,3 за палец); яд и иссушение не берут", "Sukuna's fingers give health and damage (+0.3 per finger); immune to poison and wither"),
 "role.vaz2109.vessel.p2": ("Съел палец — Сукуна овладевает телом и бьёт Фугой, а с 15 пальцев раскрывает Гробницу зла", "Eat a finger and Sukuna takes over, casting Fuga, and from 15 fingers the Malevolent Shrine"),
 "tooltip.vaz2109.sukuna_finger.2": ("Каждый палец: +½ сердца, +0,3 урона, удары по проклятиям сильнее на 5%", "Each finger: +½ heart, +0.3 damage, 5% stronger hits on curses"),
 "ability.vaz2109.piercing_blood": ("Пронзающая кровь", "Piercing Blood"),
 "ability.vaz2109.turret": ("Самодельная турель", "Home-made Turret"),
 "ability.vaz2109.swamp_pack": ("Болотная стая", "Swamp Pack"),
 "ability.vaz2109.fire_breath": ("Огненный перегар", "Fire Breath"),
 "gui.vaz2109.ability.need_trial": ("%s; %s", "%s; %s"),
 "gui.vaz2109.trial.painting": ("съесть Картину смерти", "eat the Death Painting"),
 "gui.vaz2109.trial.full_tune": ("прокатиться на полностью затюнингованной девятке (все 5 деталей)", "ride a fully tuned VAZ-2109 (all 5 parts)"),
 "gui.vaz2109.trial.jumps": ("сделать %s прыжков", "jump %s times"),
 "gui.vaz2109.trial.beers": ("выпить %s кружек пива", "drink %s beers"),
 "message.vaz2109.trial.progress": ("%s: %s/%s", "%s: %s/%s"),
 "message.vaz2109.blood.too_weak": ("Слишком мало крови, чтобы её сжать", "Too little blood left to compress"),
 "hud.vaz2109.blood.charging": ("Сжатие крови...", "Convergence..."),
 "hud.vaz2109.blood.ready": ("Отпусти: Пронзающая кровь!", "Release: Piercing Blood!"),
 "message.vaz2109.turret.no_room": ("Здесь некуда поставить турель", "No room for the turret here"),
 "message.vaz2109.turret.no_ammo": ("Турели нечем стрелять: нужны патроны 9×18", "The turret is dry: it needs 9x18 rounds"),
 "entity.vaz2109.turret": ("Самодельная турель", "Home-made Turret"),
 "entity.vaz2109.ally_frog": ("Болотная лягушка", "Swamp Frog"),
 "entity.vaz2109.choso": ("Чосо", "Choso"),
 "item.vaz2109.choso_spawn_egg": ("Яйцо призыва Чосо", "Choso Spawn Egg"),
 "item.vaz2109.death_painting": ("Картина смерти", "Death Painting"),
 "tooltip.vaz2109.death_painting": ("Утроба Картины смерти. В ней кровь рода Камо", "A Death Painting womb. The blood of the Kamo clan"),
 "tooltip.vaz2109.death_painting.1": ("Съесть может только Сосуд: +4 сердца", "Only the Vessel can eat it: +4 hearts"),
 "tooltip.vaz2109.death_painting.2": ("Открывает «Пронзающую кровь»: зажми и отпусти клавишу класса", "Unlocks Piercing Blood: hold and release the class key"),
 "message.vaz2109.painting.already": ("Кровь Картины смерти уже течёт в тебе", "The Death Painting's blood already runs in you"),
 "message.vaz2109.painting.reject": ("Это проклятая утроба. Тебя выворачивает: ты не сосуд!", "A cursed womb. Your body rejects it: you are no vessel!"),
 "message.vaz2109.painting.eaten": ("Ты поглотил Картину смерти. Кровь рода Камо подчиняется тебе.", "You absorbed the Death Painting. The Kamo blood obeys you now."),
 "quest.vaz2109.choso": ("Чосо", "Choso"),
 "quest.vaz2109.choso.desc": ("Старший из братьев Картины смерти. Управляет кровью: сжимает её и бьёт Пронзающей кровью (уходи с линии, пока он целится), вблизи взрывает Сверхновую, раненым покрывается кровяной бронёй, а на половине здоровья ускоряется Течением красной чешуи.", "Eldest of the Death Painting brothers. Blood Manipulation: Piercing Blood (step off the line while he aims), Supernova up close, blood armour when hurt and Flowing Red Scale at half health."),
 "quest.vaz2109.choso.hint": ("Полуразрушенный дом у заросшего пруда: болота, мангровые болота, тёмный и берёзовый лес.", "A half-collapsed house by an overgrown pond: swamps, mangrove swamps, dark and birch forests."),
 "quest.vaz2109.choso.coming": ("Пахнет кровью... Чосо идёт мстить за братьев.", "The smell of blood... Choso comes to avenge his brothers."),
 "chat.vaz2109.choso": ("<Чосо> %s", "<Choso> %s"),
 "chat.vaz2109.choso.start": ("Ты убил моих братьев? Тогда живым ты отсюда не уйдёшь.", "You killed my brothers? Then you don't leave here alive."),
 "chat.vaz2109.choso.pierce": ("Пронзающая кровь.", "Piercing Blood."),
 "chat.vaz2109.choso.nova": ("Сверхновая!", "Supernova!"),
 "chat.vaz2109.choso.armor": ("Кровь... затвердей.", "Blood... harden."),
 "chat.vaz2109.choso.scale": ("Течение красной чешуи!", "Flowing Red Scale!"),
 "chat.vaz2109.choso.death": ("Братья... простите меня...", "Brothers... forgive me..."),
 "commands.vaz2109.test.unlock": ("Все способности открыты (тест) у игроков: %s. Перезарядки сброшены", "All abilities unlocked (test) for %s player(s); cooldowns cleared"),
 "commands.vaz2109.test.lock": ("Тестовое открытие способностей снято у игроков: %s", "Test unlock removed for %s player(s)"),
 "commands.vaz2109.test.cooldowns": ("Перезарядки сброшены у игроков: %s", "Cooldowns cleared for %s player(s)"),
 "commands.vaz2109.test.trials": ("Все испытания выполнены у игроков: %s", "All trials completed for %s player(s)"),
 "commands.vaz2109.test.bosses": ("Все боссы отмечены побеждёнными у игроков: %s", "All bosses marked as beaten for %s player(s)"),
 "commands.vaz2109.test.fingers": ("Пальцев Сукуны: %s (игроков: %s)", "Sukuna's fingers set to %s for %s player(s)"),
 "hud.vaz2109.blood.charging": ("Сжатие крови...", "Convergence..."),
 "hud.vaz2109.blood.ready": ("ПРОНЗАЮЩАЯ КРОВЬ — нажми G ещё раз, чтобы остановить", "PIERCING BLOOD — press G again to stop"),
 "hud.vaz2109.dismantle.charging": ("Разрезов: %s / %s — отпусти", "Slashes: %s / %s — release"),
 "tooltip.vaz2109.death_painting.2": ("Открывает «Пронзающую кровь»: нажми клавишу класса — кровь сжимается и бьёт струя, нажми ещё раз — стоп (тратит здоровье)", "Unlocks Piercing Blood: press the class key to compress blood and fire the jet, press again to stop (costs health)"),
 "item.vaz2109.scooter": ("Самокат", "Kick Scooter"),
 "entity.vaz2109.scooter": ("Самокат", "Kick Scooter"),
 "entity.vaz2109.blood_beam": ("Пронзающая кровь", "Piercing Blood"),
 "tooltip.vaz2109.scooter.ride": ("ПКМ — встать. W — оттолкнуться, A/D — руль, S — задний тормоз, Пробел — прыжок", "Right-click to ride. W kick, A/D steer, S rear brake, Space hop"),
 "tooltip.vaz2109.scooter.pickup": ("Shift + ПКМ по самокату — сложить и забрать", "Shift + right-click it to fold and pick up"),
 "block.vaz2109.computer": ("Компьютер", "Computer"),
 "gui.vaz2109.pc.title": ("VAZ-OS · Рынок", "VAZ-OS · Market"),
 "gui.vaz2109.pc.sell": ("Продать", "Sell"),
 "gui.vaz2109.pc.sell_same": ("Продать все такие", "Sell all like it"),
 "gui.vaz2109.pc.sell_title": ("Продажа", "Sell"),
 "gui.vaz2109.pc.shop_title": ("Магазин", "Shop"),
 "gui.vaz2109.pc.drop_here": ("Положи предмет в слот", "Put an item in the slot"),
 "gui.vaz2109.pc.shop_hint": ("ЛКМ — купить, Shift — ×10", "Click to buy, Shift for x10"),
 "gui.vaz2109.wheel.title": ("Способности", "Abilities"),
 "key.vaz2109.class": ("Способность класса: применить (Shift — листать)", "Class ability: use (Shift to cycle)"),
 "key.vaz2109.wheel": ("Колесо способностей", "Ability wheel"),
 "gui.vaz2109.wheel.hint": ("Наведи мышью и отпусти [%s] — или кликни", "Point with the mouse and release [%s], or click"),
 "message.vaz2109.ability.unlocked": ("Открыта способность: %s! G — применить, Z — колесо способностей.", "Ability unlocked: %s! G to use, Z for the ability wheel."),
 "message.vaz2109.role.chosen": ("Твой класс: %s. G — применить способность, Z (зажать) — колесо, чтобы выбрать другую.", "Your class: %s. G uses the ability, hold Z for the wheel to pick another."),
 "item.vaz2109.banknote_100": ("Купюра 100 ₽", "100 ₽ Banknote"),
 "item.vaz2109.banknote_1000": ("Купюра 1000 ₽", "1000 ₽ Banknote"),
 "tooltip.vaz2109.banknote": ("Номинал: %s ₽", "Face value: %s ₽"),
 "tooltip.vaz2109.banknote.use": ("ПКМ — зачислить на счёт. Можно отдать другому игроку", "Right-click to deposit. Can be handed to other players"),
 "message.vaz2109.banknote.deposit": ("+%s ₽ на счёт (баланс: %s ₽)", "+%s ₽ deposited (balance: %s ₽)"),
 "gui.vaz2109.pc.worth": ("Получишь: %s ₽", "You get: %s ₽"),
 "gui.vaz2109.pc.demand": ("Спрос: %s%%", "Demand: %s%%"),
 "gui.vaz2109.pc.demand_hint": ("Завтра спрос восстановится", "Demand recovers tomorrow"),
 "gui.vaz2109.pc.new_day": ("Новый день через %s мин", "New day in %s min"),
 "gui.vaz2109.pc.tab.deals": ("Скидки дня: −30%%", "Deals of the day: −30%%"),
 "gui.vaz2109.pc.tab.food": ("Еда", "Food"),
 "gui.vaz2109.pc.tab.resources": ("Ресурсы", "Resources"),
 "gui.vaz2109.pc.tab.gear": ("Снаряжение", "Gear"),
 "gui.vaz2109.pc.tab.magic": ("Зачарования и зелья", "Enchantments and potions"),
 "gui.vaz2109.pc.tab.bank": ("Банк: купюры", "Bank: banknotes"),
 "gui.vaz2109.pc.tab.orders": ("Заказы на сегодня", "Today's orders"),
 "gui.vaz2109.pc.deals_hint": ("Каждый день — 4 новых товара", "4 new deals every day"),
 "gui.vaz2109.pc.order_hint": ("Принеси — заплатим выше рынка", "Bring it, paid above market"),
 "gui.vaz2109.pc.order.reward": ("Награда: %s ₽", "Reward: %s ₽"),
 "gui.vaz2109.pc.order.done": ("✔ Выполнено", "✔ Done"),
 "gui.vaz2109.pc.order.ready": ("Нажми, чтобы сдать (%s/%s)", "Click to hand in (%s/%s)"),
 "gui.vaz2109.pc.order.have": ("Есть: %s/%s", "Have: %s/%s"),
 "gui.vaz2109.pc.lot": ("%s ₽ за %s шт.", "%s ₽ for %s"),
 "gui.vaz2109.pc.resale": ("Компьютер выкупит: %s ₽/шт.", "The computer buys it back for %s ₽ each"),
 "gui.vaz2109.pc.no_resale": ("Компьютер это не выкупает", "The computer does not buy this back"),
 "message.vaz2109.ability.black_flash": ("15 пальцев: удар Расходящимся кулаком с полного замаха может высечь Чёрную вспышку (15%, «в потоке» 30%)!", "15 fingers: a fully charged Divergent Fist can spark a Black Flash (15%, 30% in the zone)!"),
 "tooltip.vaz2109.slaughter_demon.2": ("Удар в полную силу может стать Чёрной вспышкой (8%, «в потоке» 20%): урон ×2, затем 10 сек «в потоке» со скоростью", "A full-strength hit can become a Black Flash (8%, 20% in the zone): x2 damage, then 10 s in the zone with Speed"),
 "item.vaz2109.red_gloves": ("Красные перчатки Итадори", "Itadori's Red Gloves"),
 "tooltip.vaz2109.red_gloves": ("Перчатки Юдзи из последней арки манги", "Yuji's gloves from the manga's final arc"),
 "tooltip.vaz2109.red_gloves.1": ("Быстрые удары в крови: замедляют цель, без размашистых атак", "Fast blood-soaked punches that slow the target; no sweeping"),
 "tooltip.vaz2109.red_gloves.2": ("Сосуду — как голые кулаки: Расходящийся кулак работает, Чёрная вспышка +5%", "For the Vessel they count as bare fists: Divergent Fist works, Black Flash +5%"),
 "item.vaz2109.cigarettes": ("Сигарета", "Cigarette"),
 "tooltip.vaz2109.cigarettes": ("Зажми ПКМ — закурить: «Спешка» на 45 сек, но кружится голова (Пивовару нипочём). Больше 5 подряд — кашель, слабость и голод", "Hold right-click to smoke: Haste for 45 s, but your head spins (not the Brewer). More than 5 in a row: coughing, weakness and hunger"),
 "tooltip.vaz2109.cigarettes.left": ("Осталось сигарет: %s", "Cigarettes left: %s"),
 "tooltip.vaz2109.cigarettes.warning": ("Минздрав предупреждает: курение вредит вашему здоровью", "Smoking seriously harms your health"),
 "message.vaz2109.smoke.cough": ("Кхе-кхе... Ты накурился до тошноты", "Cough, cough... you've smoked yourself sick"),
 "message.vaz2109.smoke.wet": ("Под водой не покуришь", "You can't smoke under water"),
 "item.vaz2109.kvass": ("Квас", "Kvass"),
 "item.vaz2109.wine": ("Вино", "Wine"),
 "item.vaz2109.champagne": ("Шампанское", "Champagne"),
 "item.vaz2109.vodka": ("Водка", "Vodka"),
 "item.vaz2109.cognac": ("Коньяк", "Cognac"),
 "item.vaz2109.moonshine": ("Самогон", "Moonshine"),
 "tooltip.vaz2109.kvass": ("Безалкогольный: утоляет голод и даёт скорость на 30 сек", "Non-alcoholic: fills you up and gives Speed for 30 s"),
 "tooltip.vaz2109.wine": ("Сила на 45 сек и немного лечит", "Strength for 45 s and a little healing"),
 "tooltip.vaz2109.champagne": ("Пузырьки: скорость и прыгучесть на минуту", "Bubbles: Speed and Jump Boost for a minute"),
 "tooltip.vaz2109.vodka": ("Сопротивление урону на минуту, согревает: снимает заморозку и огонь", "Resistance for a minute; warms you up: thaws and puts out fire"),
 "tooltip.vaz2109.cognac": ("Сила на 1,5 мин и 2 сердца поглощения", "Strength for 1.5 min and 2 absorption hearts"),
 "tooltip.vaz2109.moonshine": ("Сила II и огнестойкость, но мутит, а иногда и травит (25%)", "Strength II and Fire Resistance, but nauseating and sometimes poisonous (25%)"),
 "tooltip.vaz2109.drink.units": ("Алкоголь: %s ед. Кружит голову всем, кроме Пивовара", "Alcohol: %s units. Spins everyone's head but the Brewer's"),
 "tooltip.vaz2109.drink.soft": ("Без алкоголя", "Alcohol-free"),
 "message.vaz2109.drunk.1": ("Голова кружится...", "Your head is spinning..."),
 "message.vaz2109.drunk.2": ("Ноги заплетаются. Может, хватит?", "Your legs are tangling. Maybe that's enough?"),
 "message.vaz2109.drunk.3": ("Тебе плохо. Перебрал!", "You feel awful. Way too much!"),
 "tooltip.vaz2109.beer": ("Сила на минуту, но голова кружится (алкоголь: 1 ед.)", "Strength for a minute, but your head spins (alcohol: 1 unit)"),
 "tooltip.vaz2109.beer.brewer": ("Пивовару: Сила II и лечение, без тошноты, а пьянеет вдвое медленнее", "Brewer: Strength II and healing, no nausea, and gets drunk half as fast"),
 "gui.vaz2109.pc.mode.market": ("Рынок", "Market"),
 "gui.vaz2109.pc.mode.orders": ("Заказы", "Orders"),
 "gui.vaz2109.pc.mode.casino": ("Казино", "Casino"),
 "gui.vaz2109.pc.mode.invest": ("Инвестиции", "Invest"),
 "gui.vaz2109.pc.mode.orders.title": ("Заказы на сегодня", "Today's orders"),
 "gui.vaz2109.pc.balance": ("%s ₽", "%s ₽"),
 "gui.vaz2109.pc.tab.bar": ("Бар: напитки и сигареты", "Bar: drinks and cigarettes"),
 "gui.vaz2109.pc.tab.weapons": ("Оружие и броня", "Weapons and armour"),
 "gui.vaz2109.pc.tab.misc": ("Разное и верстаки", "Misc and benches"),
 "gui.vaz2109.pc.tab.rides": ("Транспорт", "Transport"),
 "gui.vaz2109.pc.casino.bet": ("Ставка:", "Bet:"),
 "gui.vaz2109.pc.casino.slots": ("Слоты", "Slots"),
 "gui.vaz2109.pc.casino.spin": ("Крутить — %s ₽", "Spin — %s ₽"),
 "gui.vaz2109.pc.casino.roulette": ("Рулетка", "Roulette"),
 "gui.vaz2109.pc.casino.red": ("Красное ×2", "Red x2"),
 "gui.vaz2109.pc.casino.black": ("Чёрное ×2", "Black x2"),
 "gui.vaz2109.pc.casino.zero": ("0 ×36", "0 x36"),
 "gui.vaz2109.pc.casino.won": ("Выигрыш: %s ₽!", "You won %s ₽!"),
 "gui.vaz2109.pc.casino.lost": ("Мимо. Казино в плюсе", "No luck. The house wins"),
 "gui.vaz2109.pc.casino.pay1": ("3 одинаковых: ×5 ... ×500 (ВАЗ)", "Three of a kind: x5 ... x500 (VAZ)"),
 "gui.vaz2109.pc.casino.pay2": ("Пара (кроме ягод): ставка назад", "A pair (not berries): bet back"),
 "gui.vaz2109.pc.casino.pay3": ("Пара алмазов ×2, пара ВАЗов ×4", "Two diamonds x2, two VAZes x4"),
 "gui.vaz2109.pc.casino.hint": ("Отдача: слоты 93%%, рулетка 97%%", "Return: slots 93%%, roulette 97%%"),
 "message.vaz2109.casino.jackpot": ("%s сорвал джекпот в казино VAZ-OS: %s ₽!", "%s hit the VAZ-OS jackpot: %s ₽!"),
 "gui.vaz2109.pc.stock.0": ("ВАЗ-Моторс", "VAZ Motors"),
 "gui.vaz2109.pc.stock.1": ("Пивзавод «Андрей»", "Andrey Brewery"),
 "gui.vaz2109.pc.stock.2": ("СукунаКоин", "SukunaCoin"),
 "gui.vaz2109.pc.stock.have": ("Акций: %s", "Shares: %s"),
 "gui.vaz2109.pc.stock.sell_all": ("Продать", "Sell all"),
 "gui.vaz2109.pc.deposit": ("Вклад +1%%/день: %s ₽", "Deposit +1%%/day: %s ₽"),
 "gui.vaz2109.pc.deposit.take": ("Снять", "Withdraw"),
 "gui.vaz2109.pc.invest_hint": ("Комиссия 3%% · цена меняется раз в день", "3%% fee · prices change daily"),
}
for k, (r, e) in R.items():
    d[k] = r if ru else e
json.dump(d, open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
print(len(d))
