"""Generates SukunaTrack.java: the hits of the awakening track in game ticks. BIG = kick-band spikes (40-160 Hz),
SMALL = hi-hat-band spikes (>2.5 kHz), each a loudness jump over the previous half second, at least 5 ticks apart.
usage: trackhits.py low.raw high.raw out.java"""
import sys
import numpy as np
sr = 11025; step = sr // 20
def env(f):
    x = np.fromfile(f, dtype=np.float32); n = len(x) // step
    return np.sqrt((x[:n * step].reshape(n, step) ** 2).mean(1))
def hits(e, ratio=1.25):
    out, last = [], -99
    floor = np.percentile(e, 40)
    for t in range(10, len(e) - 1):
        if e[t] > e[t - 10:t].mean() * ratio and e[t] >= e[t - 1] and e[t] >= e[t + 1] and e[t] > floor and t - last >= 5:
            out.append(t); last = t
    return out
lo, hi = env(sys.argv[1]), env(sys.argv[2])
big = hits(lo); small = [t for t in hits(hi) if all(abs(t - b) >= 3 for b in big)]
length = len(lo)
J = ['package com.bobux.vaz2109.entity.curse;', '',
     '/** Generated by tools/trackhits.py from the awakening track. Hits in game ticks from the start of the track. */',
     'final class SukunaTrack {', f'   static final int LENGTH = {length};',
     '   static final int[] BIG = new int[]{' + ', '.join(map(str, big)) + '};',
     '   static final int[] SMALL = new int[]{' + ', '.join(map(str, small)) + '};', '',
     '   private SukunaTrack() {', '   }', '}', '']
open(sys.argv[3], 'w').write('\n'.join(J))
print(length, 'ticks;', len(big), 'big hits,', len(small), 'small hits')
